# Generated by Django 5.2 on 2025-04-08 07:27

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('allergies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dairy', 'Dairy'), ('Gluten', 'Gluten'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Soy', 'Soy'), ('Eggs', 'Eggs'), ('Shellfish', 'Shellfish'), ('Fish', 'Fish'), ('Sesame', 'Sesame'), ('Wheat', 'Wheat')], max_length=62)),
                ('fatty_acid_report', models.FileField(upload_to='reports/')),
                ('stage', models.CharField(choices=[('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2'), ('Stage 3', 'Stage 3'), ('Stage 4', 'Stage 4')], default='Stage 1', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
