# Generated by Django 5.2 on 2025-04-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_foodlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('breakfast', models.TextField(blank=True)),
                ('lunch', models.TextField(blank=True)),
                ('dinner', models.TextField(blank=True)),
                ('snacks', models.TextField(blank=True)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='tracker.userprofile')),
            ],
        ),
    ]
