# Generated by Django 5.2 on 2025-04-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dietplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stage',
        ),
    ]
