# Generated by Django 5.2 on 2025-04-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_userprofile_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fatty_acid_report',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
    ]
