# Generated by Django 5.2 on 2025-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_userprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Gluten', 'Gluten'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Soy', 'Soy'), ('Eggs', 'Eggs'), ('Shellfish', 'Shellfish'), ('Fish', 'Fish'), ('Sesame', 'Sesame'), ('Wheat', 'Wheat')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
