# Generated by Django 5.2 on 2025-04-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_userprofile_allergies_userprofile_diet_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liver_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sgot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sgpt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
