# Generated by Django 5.2 on 2025-04-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_userprofile_liver_stage_userprofile_sgot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sgot',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sgpt',
        ),
    ]
