# Generated by Django 5.2 on 2025-04-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_userprofile_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='allergy_to_avoid',
            field=models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Gluten', 'Gluten'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Soy', 'Soy'), ('Eggs', 'Eggs'), ('Shellfish', 'Shellfish'), ('Fish', 'Fish'), ('Sesame', 'Sesame'), ('Wheat', 'Wheat')], max_length=100),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='liver_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
