# Generated by Django 5.2 on 2025-04-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_dietplan_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='allergy_to_avoid',
            field=models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Gluten', 'Gluten'), ('Nuts', 'Nuts'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Gluten', 'Gluten'), ('Nuts', 'Nuts'), ('None', 'None')], max_length=100),
        ),
    ]
