# Generated by Django 5.2 on 2025-05-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_dietplan_allergy_to_avoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='allergy_to_avoid',
            field=models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Nuts', 'Nuts'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Nuts', 'Nuts'), ('None', 'None')], max_length=100),
        ),
    ]
